spring:
  devtools:
    add-properties: false

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

source-diff:
  host:
  show-line-count: 30
  repositories:
    - name:
      dev-url:
      dev-username:
      dev-password:
      prod-url:
      prod-username:
      prod-password:
      receivers:

file-filter:
  prefix:
  postfix:
  contains:

mailing:
  enabled: false
  host: