server:
  compression:
    enabled: true

spring:
  data:
    web:
      pageable:
        default-page-size: 2000
        max-page-size: 5000

  devtools:
    add-properties: false

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  web:
    resources:
      cache:
        period: 86400

springdoc.swagger-ui.path: /swagger-ui.html

source-diff:
  host:
  show-line-count: 30
  repositories:
    - name:
      dev-url:
      dev-username:
      dev-password:
      prod-url:
      prod-username:
      prod-password:
      receivers:

file-filter:
  prefix:
  postfix:
  contains:

mailing:
  enabled: false
  host:

scheduler:
  enabled: false
  scan: 120000
  mailing: 0 0 8 * * 1-5